import express from "express";
import db from "../db/connection.js";
import { ObjectId } from "mongodb";
import { Poll } from "../models/poll.js";
import { Vote } from "../models/vote.js";

const router = express.Router();

// Create a poll.
router.post("/create", async (req, res) => {
	// Create the poll object.
	const { title, options, endsAt }: Partial<Poll> = req.body;
	const createdAt = new Date();
	const document: Partial<Poll> = {
		title,
		options,
		createdAt,
		endsAt,
	};
	// Insert the document.
	let result = await db.collection("polls").insertOne(document);
	// Send back the objectID generated by MongoDB.
	res.send(result.insertedId).status(201);
});

// Get a poll.
router.get("/:id", async (req, res) => {});

// Get a poll's results.
router.get("/:id/results", async (req, res) => {});

// Vote in a poll.
router.post("/:id/vote", async (req, res) => {});

export default router;
