import express from "express";
import db from "../db/connection.js";
import { ObjectId } from "mongodb";
import { Poll, Option } from "../models/poll.js";
import { Vote } from "../models/vote.js";

const router = express.Router();

// Create a poll.
router.post("/create", async (req, res) => {
	const { title, options, endsAt } = req.body;

	// Create options array with ids.
	const optionsWithIds: Option[] = options.map(
		(option: string, index: number) => ({
			id: index.toString(),
			title: option,
		})
	);

	// Create the poll object.
	const createdAt = new Date();
	const document: Partial<Poll> = {
		title,
		options: optionsWithIds,
		createdAt,
		endsAt,
	};

	// Insert the document.
	let result = await db.collection("polls").insertOne(document);

	// Send back the objectID generated by MongoDB.
	res.send(result.insertedId).status(201);
});

// Get a poll.
router.get("/:id", async (req, res) => {});

// Get a poll's results.
router.get("/:id/results", async (req, res) => {});

// Vote in a poll.
router.post("/:id/vote", async (req, res) => {});

export default router;
